import os
from pathlib import Path

import yaml
from crewai import Agent, Crew, Process, Task, LLM
from crewai.project import CrewBase, agent, crew, task
from crewai.agents.agent_builder.base_agent import BaseAgent
from typing import List

_CONFIG_DIR = Path(__file__).resolve().parent / "config"


def _load_yaml(name: str) -> dict:
    with open(_CONFIG_DIR / name, encoding="utf-8") as f:
        return yaml.safe_load(f)


def load_brand_inputs() -> dict:
    """Load the brand inputs used to fill the {brand}/{product}/... placeholders.

    Prefers the git-ignored ``brand.local.yaml`` (your real, private brand
    details) and falls back to the committed ``brand.example.yaml`` placeholders.
    """
    local = _CONFIG_DIR / "brand.local.yaml"
    example = _CONFIG_DIR / "brand.example.yaml"
    path = local if local.exists() else example
    with open(path, encoding="utf-8") as f:
        return yaml.safe_load(f)


def default_llm() -> LLM:
    """Shared LLM for the pipeline agents.

    Backend is selected via MKT_BACKEND (groq | gemini), defaulting to groq.
    The Groq path reads MKT_MODEL; the Gemini path reads MKT_MODEL_GEMINI.
    """
    backend = os.getenv("MKT_BACKEND", "groq").lower()

    if backend == "gemini":
        model = os.getenv("MKT_MODEL_GEMINI", "gemini/gemini-2.0-flash")
    else:  # groq (default)
        model = os.getenv("MKT_MODEL", "groq/llama-3.3-70b-versatile")

    return LLM(model=model, temperature=0.7)


def critic_llm() -> LLM:
    """LLM for the ad critic.

    Deliberately pinned to Groq regardless of MKT_BACKEND so scoring stays
    consistent and cheap when comparing hooks generated by different backends.
    Override with MKT_CRITIC_MODEL if needed. Temperature 0 for stable scores.
    """
    return LLM(
        model=os.getenv("MKT_CRITIC_MODEL", "groq/llama-3.3-70b-versatile"),
        temperature=0.0,
    )


@CrewBase
class MarketingCrew:
    """Research -> ad-angle pipeline for a configurable DTC brand."""

    agents: List[BaseAgent]
    tasks: List[Task]

    @agent
    def market_researcher(self) -> Agent:
        return Agent(
            config=self.agents_config["market_researcher"],
            llm=default_llm(),
            verbose=True,
        )

    @agent
    def ad_strategist(self) -> Agent:
        return Agent(
            config=self.agents_config["ad_strategist"],
            llm=default_llm(),
            verbose=True,
        )

    @task
    def research_task(self) -> Task:
        return Task(config=self.tasks_config["research_task"])

    @task
    def ad_angles_task(self) -> Task:
        return Task(config=self.tasks_config["ad_angles_task"])

    @crew
    def crew(self) -> Crew:
        return Crew(
            agents=self.agents,
            tasks=self.tasks,
            process=Process.sequential,
            verbose=True,
        )


def build_critic_crew() -> Crew:
    """Standalone critic crew that scores a set of ad hooks (from any backend).

    Always runs on Groq via critic_llm(). Built explicitly (not via @CrewBase)
    so it reads only the ad_critic / critique_ad_angles config and ignores the
    main pipeline's tasks. The description's placeholders are filled by the
    inputs passed to crew.kickoff().
    """
    acfg = _load_yaml("critic_agents.yaml")["ad_critic"]
    tcfg = _load_yaml("critic_tasks.yaml")["critique_ad_angles"]

    critic = Agent(
        role=acfg["role"],
        goal=acfg["goal"],
        backstory=acfg["backstory"],
        llm=critic_llm(),
        verbose=True,
    )
    task = Task(
        description=tcfg["description"],
        expected_output=tcfg["expected_output"],
        agent=critic,
        output_file=tcfg.get("output_file"),
    )
    return Crew(
        agents=[critic],
        tasks=[task],
        process=Process.sequential,
        verbose=True,
    )
